---
title: "Lexical decision task"
author: "Afroditi Ntourountzi"
output:
  html_document:
    mathjax: null
    highlight: null
    theme: null
    css: jspsych-6-2/css/jspsych.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
# load the plugin scripts in plugins.html which is included in the header.
```

```{r}
# load jspsych and plugin scripts
# note: this is an r code chunk
library(htmltools)
tagList(
tags$script(src='https://nedergaard.cogsci.au.dk/jspsych_workshop/jspsych/jspsych.js'),
tags$script(src='https://nedergaard.cogsci.au.dk/jspsych_workshop/jspsych/plugins/jspsych-html-keyboard-response.js'),
tags$script(src='https://nedergaard.cogsci.au.dk/jspsych_workshop/jspsych/plugins/jspsych-video-keyboard-response.js'),
tags$script(src='https://nedergaard.cogsci.au.dk/jspsych_workshop/jspsych/plugins/jspsych-instructions.js'),
tags$link(href="https://nedergaard.cogsci.au.dk/jspsych_workshop/jspsych/css/jspsych.css", rel="stylesheet"),
# tags$script(src='jspsych-6-2/plugins/jspsych-survey-text.js'),
# tags$script(src='jspsych-6-2/plugins/jspsych-survey-multi-choice.js'),
# tags$script(src='jspsych-6-2/plugins/jspsych-survey-html-form.js'),
tags$script(src='jspsychr/jspsychr.js')
)
```

```{r, results="asis"}
# Define stimuli in R, output as script 
# note: this is an r code chunk, with results = "asis"
library(jspsychr)
library(dplyr)

# test setup
stim =  c(rep(c("test", "me", "now", "really"), times=2), rep(c("tes", "ma", "nov", "rale"), times=2))
lex_test <- data.frame(word = stim,
                       word_type = c(rep(c("1", "2"), each=4), rep("3", each=8)))
                                     
# video_test = c(rep(c("test", "me"), each=2), rep(c("nov", "rale"), each=2))
video_test = rep(stim[1:(length(stim)/2)], times=4)
vid_stim_test <- data.frame( video = video_test,
                             video_source = c(paste(video_test[1:(length(video_test)/2)], "m.mp4", sep = "_"), paste(video_test[(length(video_test)/2+1):length(video_test)], "o.mp4", sep = "_")),
                             video_type = rep(c("1", "2"), each=length(video_test)/2))

# with mouthing
new_lex_test = sample(lex_test$word[5:8])
print(new_lex_test)
while (any(new_lex_test==vid_stim_test$video[5:8])) {     
new_lex_test = sample(lex_test$word[5:8])
print(new_lex_test)
}
new_lex_test_m=  vid_stim_test[5:8,]
new_lex_test_m$word = new_lex_test
new_lex_test_m$word_type = lex_test$word_type[5:8]

# without mouthing
new_lex_test = sample(lex_test$word[5:8])
print(new_lex_test)
while (any(new_lex_test==vid_stim_test$video[21:24])) {     
new_lex_test = sample(lex_test$word[5:8])
print(new_lex_test)
}
new_lex_test_o =  vid_stim_test[21:24,]
new_lex_test_o$word = new_lex_test
new_lex_test_o$word_type = lex_test$word_type[5:8]

avg_match <- function(y,z) {
  # print(y)
  # print(z)
  mean(apply(do.call(rbind, strsplit(c(y, z), "")), 2, function(x){
    # print(x)
    length(unique(x[!x %in% "_"])) == 1
  }))}

# WITH mouthing
new_pseudo_test = sample(lex_test$word[(length(stim)/2+1):length(stim)])
print(new_pseudo_test)
while (any(mapply(avg_match, new_pseudo_test, vid_stim_test$video[9:16])>0.5)) {
new_pseudo_test = sample(lex_test$word[(length(stim)/2+1):length(stim)])
print(new_pseudo_test)
}
new_pseudo_test_m =  vid_stim_test[9:16,]
new_pseudo_test_m$word = new_pseudo_test
new_pseudo_test_m$word_type = lex_test$word_type[(length(stim)/2+1):length(stim)]

# WITHOUT mouthing
new_pseudo_test = sample(lex_test$word[(length(stim)/2+1):length(stim)])
print(new_pseudo_test)
while (any(mapply(avg_match, new_pseudo_test, vid_stim_test$video[25:32])>0.5)) {
new_pseudo_test = sample(lex_test$word[(length(stim)/2+1):length(stim)])
print(new_pseudo_test)
}
new_pseudo_test_o =  vid_stim_test[25:32,]
new_pseudo_test_o$word = new_pseudo_test
new_pseudo_test_o$word_type = lex_test$word_type[(length(stim)/2+1):length(stim)]

# creating a full data frame with both written and video stimuli
# starting with the identical condition - WITH mouthing
full_test = merge(lex_test[1:4,],  vid_stim_test[1:4,], by = 0)
full_test = within(full_test, rm(Row.names))

# next are the shuffled real words
full_test = rbind(full_test, new_lex_test_m)

# next are the pseudowords
full_test = rbind(full_test, new_pseudo_test_m)

# AND NOW exactly the same - but for the NO MOUTHING condition
# starting with the identical condition - WITHOUT mouthing
temp_lex = lex_test[1:4,]
row.names(temp_lex) = row.names(vid_stim_test[17:20,])
temp_ident = merge(temp_lex,  vid_stim_test[17:20,], by = 0)
temp_ident = within(temp_ident, rm(Row.names))
full_test = rbind(full_test, temp_ident)

# next are the shuffled real words
# combing full data frame with temp df
full_test = rbind(full_test, new_lex_test_o)

# next are the pseudowords
full_test = rbind(full_test, new_pseudo_test_o)

full_test$color = 'black'
full_test$id = "lex_stim"
full_test$fontsize = "60pt"
full_test <- full_test %>% 
  mutate(response = if_else(word_type > 2, "j", "i")) %>%
  mutate(word_type = recode(word_type, "1" = "same_word", "2" = "diff_word", "3" = "pseudoword")) %>%
  mutate(video_type = recode(video_type, "1" = "mouthing", "2" = "no_mouthing"))

full_test$stimulus <- html_stimulus(df = full_test, 
                                html_content = "word",
                                html_element = "p",
                                column_names = c("color","fontsize"),
                                css = c("color", "font-size"),
                                id = "id")

# create json object from dataframe
lex_json <- stimulus_df_to_json(df = full_test,
                                     stimulus = "stimulus",
                                     data = c("word","response","word_type",
                                              "video","video_source","video_type"))

# write json object to script
write_to_script(lex_json,"lex_stimuli")

```

```{r}
# # create dataframe to define stimuli
# lex_stim <- data.frame( word = c(rep(c("βράδυ", "σελίδα", "όριο", "βήμα", "λέξη", "γραμμή", "χωριό", "αγάπη", "λάθος", "νησί", "ευθύνη", "νίκη", "ιδέα", "τίτλος", "λύση", "έρευνα", "όνομα", "σχέδιο", "νόμος", "αλλαγή"), times=2), c("βρύδα", "δασέλι", "άλιο", "μήβα", "πέξη", "τραμμή", "βωριό", "εκάπη", "κάθος", "λησί", "αυδύνη", "πίκη", "αδέα", "φίτλος", "δέκη", "άλευνα", "μάονο", "γδέσιο", "βόνος", "επαγή")),
#                         stim_type = rep(c("1", "2", "3"), times=20))
# 
# video = rep(c("βράδυ", "σελίδα", "όριο", "βήμα", "λέξη", "γραμμή", "χωριό", "αγάπη", "λάθος", "νησί", "ευθύνη", "νίκη", "ιδέα", "τίτλος", "λύση", "έρευνα", "όνομα", "σχέδιο", "νόμος", "αλλαγή"), times=2)
# vid_stim <- data.frame( video = video,
#                         video_source = c(paste(video[1:(length(video)/2)], "μ.mp4", sep = "_"), paste(video[(length(video)/2+1):length(video)], "ο.mp4", sep = "_")))
# 
#                         
# full_stim <- data.frame( stimulus = length(20*3*2),
#                            word = rep(c(rep(c("βράδυ", "σελίδα", "όριο", "βήμα", "λέξη", "γραμμή", "χωριό", "αγάπη", "λάθος", "νησί", "ευθύνη", "νίκη", "ιδέα", "τίτλος", "λύση", "έρευνα", "όνομα", "σχέδιο", "νόμος", "αλλαγή"), times=2), c("βρύδα", "δασέλι", "άλιο", "μήβα", "πέξη", "τραμμή", "βωριό", "εκάπη", "κάθος", "λησί", "αυδύνη", "πίκη", "αδέα", "φίτλος", "δέκη", "άλευνα", "μάονο", "γδέσιο", "βόνος", "επαγή")), times=2),
#                            video = rep(c("βράδυ", "σελίδα", "όριο", "βήμα", "λέξη", "γραμμή", "χωριό", "αγάπη", "λάθος", "νησί", "ευθύνη", "νίκη", "ιδέα", "τίτλος", "λύση", "έρευνα", "όνομα", "σχέδιο", "νόμος", "αλλαγή"), times=2),
#                            color = "white",
#                            response = c(rep("i", each=20, times=2), rep("j", each=20)),
#                            stim_type = c(rep(c(1:20), times=2), c(21:40)),
#                            id = "lex_stim",
#                            fontsize = "60pt") %>%
#   mutate(stim_type = recode(stim_type, "1"= same_word, "2"= diff_word, "3"=pseudoword ))
#   #mutate(stim_type = as.numeric(word==color)) %>%
#   #mutate(stim_type = recode(stim_type, `1` = "congruent", `0` = "incongruent"))
# 
# # write html definitions to the stimulus column
# # note this could be added as a pipe to the above, setting df=.
# lex_stim$stimulus <- html_stimulus(df = lex_stim, 
#                                 html_content = "word",
#                                 html_element = "p",
#                                 column_names = c("color","fontsize"),
#                                 css = c("color", "font-size"),
#                                 id = "id")
# 
# 
# 
# 
# vid_stim$stimulus <- html_stimulus(df = vid_stim, 
#                                 html_content = "word",
#                                 html_element = "p",
#                                 column_names = c("color","fontsize"),
#                                 css = c("color", "font-size"),
#                                 id = "id")
# 
# # create json object from dataframe
# lex_json <- stimulus_df_to_json(df = lex_stim,
#                                      stimulus = "stimulus",
#                                      data = c("word","color","response","stim_type"))
# 
# vid_json <- stimulus_df_to_json(df = vid_stim,
#                                      stimulus = "stimulus",
#                                      data = c("word","color","response","stim_type"))
# 
# # write json object to script
# write_to_script(lex_json,"lex_stimuli")
# write_to_script(vid_json,"vid_stimuli")
```


```{js}
/* Note this is a js (javascript) code chunk */

var shuffled_stim = jsPsych.randomization.shuffleNoRepeats(lex_stimuli, function(a,b) { return a.data.word === b.data.word });


/* experiment parameters */
var reps_per_trial_type = 1;

/*set up welcome block*/
var welcome = {
  type: "html-keyboard-response",
  stimulus: "<p>Καλώς ήρθες στο πείραμα.</p>"+
  "<p>Πάτησε οποιοδήποτε πλήκτρο για να ξεκινήσεις.</p>"
};



//Set up pre-task survey


<!-- var pre_trial_text1 = { -->
<!--   type: 'survey-text', -->
<!--   questions: [ -->
<!--     {prompt: "Por favor indique su edad.", name: 'Age', required: true}, -->
<!--     {prompt: "Por favor indique de qué país es usted.", name: 'Nationality', required: true}, -->
<!--     {prompt: "Por favor indique su país de residencia actual.", name: 'Residence', required: true} -->
<!--   ], -->
<!-- }; -->

<!-- var gend = ["Mujer", "Hombre", "Género no binario / Otro"]; -->
<!-- var y_n = ["Sí", "No"]; -->

<!-- var pre_trial_choice1 = { -->
<!--   type: 'survey-multi-choice', -->
<!--   questions: [ -->
<!--     {prompt: "Por favor indique su género.", name: 'Gender', options: gend, required: true}, -->
<!--     {prompt: "¿Su género coincide con el que le asignaron al nacer?", name: 'CisTrans', options: y_n, required: true}, -->
<!--   ], -->
<!-- }; -->

<!-- var edu = ["Educación primaria", "Educación secundaria", "Bachillerato", "Grado universitario", "Máster", "Doctorado", "Otro"]; -->

<!-- var pre_trial_choice2 = { -->
<!--   type: 'survey-multi-choice', -->
<!--   questions: [ -->
<!--     {prompt: "Por favor indique su nivel más alto de formación académica completada.", name: 'Education', options: edu, required: true}, -->
<!--   ], -->
<!-- }; -->

<!-- var pre_trial_text2 = { -->
<!--   type: 'survey-text', -->
<!--   questions: [ -->
<!--     {prompt: "Por favor indique su idioma de comunicación principal.", name: 'Language1', required: true}, -->
<!--     {prompt: "Por favor indique a qué edad adquirió el español (escriba un cero si es desde el nacimiento).", name: 'AoA', required: true} -->
<!--   ] -->
<!-- } -->

<!-- var L_box = '<option value="empty">Nivel</option> <option value="A1">Principiante (A1)</option> <option value="A2">Elemental (A2)</option> <option value="B1">Intermedio bajo (B1)</option> <option value="B2">Intermedio alto (B2)</option> <option value="C1">Avanzado (C1)</option> <option value="C2">Experto/Nativo (C2)</option> </select> </p>' -->

<!-- var pre_trial_form = { -->
<!--   type: 'survey-html-form', -->
<!--   preamble: '<p> Por favor indique qué otros idiomas habla y su nivel de competencia. </p>', -->
<!--   html: '<p> <input name="L2" type="text" /> <select name="ProficiencyL2">' + L_box + '<p> <input name="L3" type="text" /> <select name="ProficiencyL3">' + L_box + '<p> <input name="L4" type="text" /> <select name="ProficiencyL4">' + L_box + '<p> <input name="L5" type="text" /> <select name="ProficiencyL5">' + L_box + '<p> <input name="L6" type="text" /> <select name="ProficiencyL6">' + L_box + '<p> <input name="L7" type="text" /> <select name="ProficiencyL7">' + L_box + '<p> <input name="L8" type="text" /> <select name="ProficiencyL8">' + L_box + '<p> <input name="L9" type="text" /> <select name="ProficiencyL9">' + L_box + '<p> <input name="L10" type="text" /> <select name="ProficiencyL10">' + L_box + '<p> <input name="L11" type="text" /> <select name="ProficiencyL11">' + L_box, -->
<!--   autofocus: 'test-resp-box' -->
<!-- }; -->

<!-- var pre_trial_choice3 = { -->
<!--   type: 'survey-multi-choice', -->
<!--   questions: [ -->
<!--     {prompt: "¿Padece usted de algún tipo de daltonismo?", name: 'Colour-blindness', options: y_n, required: true}, -->
<!--     {prompt: "¿Tiene usted un historial o padece actualmente de alguna enfermedad neurológica (incluyendo síntomas de déficit de atención)?", name: 'Disease', options: y_n, required: true}, -->
<!--   ], -->
<!-- } -->



/*set up instructions block*/
var instructions = {
  type: "html-keyboard-response",
  stimulus: "<p>Πρόκειται να δεις ένα βίντεο με κάποιον που νοηματίζει μια λέξη" +
      "<p>και έπειτα, μία γραπτή λέξη θα εμφανιστεί στην οθόνη σου."+
      "<p>Θα θέλαμε να αποφασίσεις όσο πιο γρήγορα μπορείς, εάν η γραπτή λέξη " + 
      "<p>είναι πραγματική ελληνική λέξη ή όχι.\n\n\n"+
      "<p>Πάτησε <b>"I"</b> στο πληκτρολόγιό σου εάν νομίζεις ότι <b>ΔΕΝ</b> είναι πραγματική λέξη." +
      "<p>Πάτησε <b>"J"</b> στο πληκτρολόγιό σου εάν νομίζεις ότι <b>ΕΙΝΑΙ</b> πραγματική λέξη.\n\n\n" +
      "<p>Πάτησε το πλήκτρο για να ξεκινήσεις.</p>",
  post_trial_gap: 1000
};

var fixation = {
    type: 'html-keyboard-response',
    stimulus: '<div style="font-size:60px;">+</div>',
    choices: jsPsych.NO_KEYS,
    trial_duration: 1000
}

var video = {
    type: 'video-keyboard-response',
    data: jsPsych.timelineVariable('data'),
    sources: data.video_source
        
    margin_vertical: '10px',
    height: '300px', 
    choices: jsPsych.NO_KEYS,
    trial_ends_after_video: true,
    timeline_variables: shuffled_stimuli,
}

var fixation_2 = {
    type: 'html-keyboard-response',
    stimulus: '<div style="font-size:60px;">+</div>',
    choices: jsPsych.NO_KEYS,
    trial_duration: 1000
}

/* defining test timeline */
var test = {
  timeline: [{
    type: 'html-keyboard-response',
    choices: ["i","j"],
    trial_duration: 2000,
    response_ends_trial: true,
    stimulus: jsPsych.timelineVariable('stimulus'),
    data: jsPsych.timelineVariable('data'),
    on_finish: function(data){
      var correct = false;
      if(data.response == 'i' &&  data.key_press == 105 && data.rt > -1){
        correct = true;
      } else if(data.response == 'j' &&  data.key_press == 106 && data.rt > -1){
        correct = true;
      } 
      data.correct = correct;
    },
    post_trial_gap: function() {
        return Math.floor(Math.random() * 1500) + 500;
    }
  }],
  timeline_variables: shuffled_stimuli,
  /*sample: {type: 'fixed-repetitions', size: reps_per_trial_type}*/
};

/*defining debriefing block*/
var debrief = {
  type: "html-keyboard-response",
  stimulus: function() {
    var congruent_rt = Math.round(jsPsych.data.get().filter({correct: true, stim_type: 'congruent'}).select('rt').mean());
    var incongruent_rt = Math.round(jsPsych.data.get().filter({correct: true, stim_type: 'incongruent'}).select('rt').mean());
    return "<p>Your average response time for congruent trials was <strong>" + congruent_rt + "ms</strong>.</p>"+
    "<p>Your average response time for incongruent trials was <strong>" + incongruent_rt + "ms</strong>.</p>"+
    "<p>Press any key to complete the experiment. Thank you!</p>";
  }
};

/*defining thank-you node*/
var thanks = {
  type: "html-keyboard-response",
  stimulus: "<p>Ευχαριστούμε για τη συμμετοχή σου!</p>"+
  "<p>Πάτησε οποιοδήποτε πλήκτρο για να ολοκληρωθεί το πείραμα.</p>",
};

/*defining fullscreen node*/
var fullscreen = {
  type: "fullscreen",
  fullscreen_mode: true
};

/*set up experiment structure*/
var timeline = [];
timeline.push(fullscreen)
timeline.push(welcome);
timeline.push(instructions);
timeline.push(fixation);
timeline.push(video);
timeline.push(fixation);
timeline.push(test);
timeline.push(thanks)
/*timeline.push(debrief);*/

/*start experiment*/
jsPsych.init({
    timeline: timeline,
    on_finish: function() {
        jsPsych.data.displayData();
  jsPsych.data.get().localSave('csv','stroop_results_test.csv');
    }
});
```
